In [1]:
import yfinance as yf

---
##### 'AAPL' 이라는 티커를 가진 종목의 주가를 start에 설정한 날짜부터 오늘까지 전부 받아올 수 있는 코드
    - 만약 원하는 기간이 있다면 파라미터에 end = '2019-06-01'를 추가로 넣으면 된다.

---

In [2]:
yf.download('AAPL',start = '2022-01-01')

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2022-01-03,177.830002,182.880005,177.710007,182.009995,180.434296,104487900
2022-01-04,182.630005,182.940002,179.119995,179.699997,178.144302,99310400
2022-01-05,179.610001,180.169998,174.639999,174.919998,173.405701,94537600
2022-01-06,172.699997,175.300003,171.639999,172.000000,170.510971,96904000
2022-01-07,172.889999,174.139999,171.029999,172.169998,170.679474,86709100
...,...,...,...,...,...,...
2023-06-15,183.960007,186.520004,183.779999,186.009995,186.009995,65433200
2023-06-16,186.729996,186.990005,184.270004,184.919998,184.919998,101235600
2023-06-20,184.410004,186.100006,184.410004,185.009995,185.009995,49799100
2023-06-21,184.899994,185.410004,182.589996,183.960007,183.960007,49477400
2023-06-22,183.740005,185.880005,183.669998,185.725006,185.725006,12291498

---
##### 한 번에 여러 종목 받아오기

In [12]:
data = yf.download(('AAPL','MSFT'),start = '2022-01-01')

[*********************100%***********************]  2 of 2 completed

---
##### 원하는 데이터 종류 가져오깅

In [13]:
data['Close']

                  AAPL        MSFT
Date
2022-01-03  182.009995  334.750000
2022-01-04  179.699997  329.010010
2022-01-05  174.919998  316.380005
2022-01-06  172.000000  313.880005
2022-01-07  172.169998  314.040009
...                ...         ...
2023-06-15  186.009995  348.100006
2023-06-16  184.919998  342.329987
2023-06-20  185.009995  338.049988
2023-06-21  183.960007  333.559998
2023-06-22  185.899994  336.640015

[369 rows x 2 columns]

---
##### yfinance로 주가 외 데이터 받아오기

    - yf.Ticker() 함수를 통해 내가 데이터를 받고자 하는 기업의 티커를 전달해주자

In [5]:
aapl = yf.Ticker('AAPL')

---
- 배당 내역

In [6]:
aapl.dividends

Date
1987-05-11 00:00:00-04:00    0.000536
1987-08-10 00:00:00-04:00    0.000536
1987-11-17 00:00:00-05:00    0.000714
1988-02-12 00:00:00-05:00    0.000714
1988-05-16 00:00:00-04:00    0.000714
                               ...
2022-05-06 00:00:00-04:00    0.230000
2022-08-05 00:00:00-04:00    0.230000
2022-11-04 00:00:00-04:00    0.230000
2023-02-10 00:00:00-05:00    0.230000
2023-05-12 00:00:00-04:00    0.240000
Name: Dividends, Length: 79, dtype: float64

---
- 주식분할 내역

In [7]:
aapl.splits

Date
1987-06-16 00:00:00-04:00    2.0
2000-06-21 00:00:00-04:00    2.0
2005-02-28 00:00:00-05:00    2.0
2014-06-09 00:00:00-04:00    7.0
2020-08-31 00:00:00-04:00    4.0
Name: Stock Splits, dtype: float64

---
- 애널리스트 평가 정보

In [8]:
aapl.recommendations()

YFNotImplementedError: Have not implemented fetching 'recommendations' from Yahoo API

---
##### 마이크로소프트 주식 설정
---

In [14]:
msft = yf.Ticker("MSFT")

---
##### 마이크로소프트 정보

In [15]:
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'fax': '425 706 7329',
 'website': 'https://www.microsoft.com',
 'industry': 'Software—Infrastructure',
 'industryDisp': 'Software—Infrastructure',
 'sector': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. The company operates in three segments: Productivity and Business Processes, Intelligent Cloud, and More Personal Computing. The Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, Microsoft Viva, and Skype for Business; Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. The Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related Client Access Licenses; GitHub that provides a collaboration platform and code hosting service for developers; Nuance provides healthcare and enterprise AI solutions; and Azure, a cloud platform. It also offers enterprise support, Microsoft consulting, and nuance professional services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. The More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; and Windows Internet of Things. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. Microsoft Corporation was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 55,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2022,
   'totalPay': 12676750,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 63,
   'title': 'Pres & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2022,
   'totalPay': 4655274,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 50,
   'title': 'Exec. VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 4637915,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson  Althoff',
   'age': 49,
   'title': 'Exec. VP & Chief Commercial Officer',
   'yearBorn': 1973,
   'fiscalYear': 2022,
   'totalPay': 4428268,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 50,
   'title': 'Exec. VP of Bus. Devel., Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2022,
   'totalPay': 4588876,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 55,
   'title': 'Corp. VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 50,
   'title': 'Exec. VP of AI & CTO',
   'yearBorn': 1972,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Gen. Mang. of Investor Relations',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Corp. VP for Corp. Communications',
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher C. Capossela',
   'age': 52,
   'title': 'Exec. VP & Chief Marketing Officer',
   'yearBorn': 1970,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 6,
 'boardRisk': 3,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 2,
 'overallRisk': 2,
 'governanceEpochDate': 1685577600,
 'compensationAsOfEpochDate': 1672444800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 333.56,
 'open': 334.12,
 'dayLow': 333.34,
 'dayHigh': 338.56,
 'regularMarketPreviousClose': 333.56,
 'regularMarketOpen': 334.12,
 'regularMarketDayLow': 333.34,
 'regularMarketDayHigh': 338.56,
 'dividendRate': 2.72,
 'dividendYield': 0.008,
 'exDividendDate': 1692144000,
 'payoutRatio': 0.28170002,
 'fiveYearAvgDividendYield': 1.09,
 'beta': 0.927464,
 'trailingPE': 36.486458,
 'forwardPE': 30.75525,
 'volume': 6255929,
 'regularMarketVolume': 6255929,
 'averageVolume': 28059312,
 'averageVolume10days': 29662380,
 'averageDailyVolume10Day': 29662380,
 'bid': 337.94,
 'ask': 337.91,
 'bidSize': 1200,
 'askSize': 1000,
 'marketCap': 2504049819648,
 'fiftyTwoWeekLow': 213.43,
 'fiftyTwoWeekHigh': 351.47,
 'priceToSalesTrailing12Months': 12.06242,
 'fiftyDayAverage': 312.8444,
 'twoHundredDayAverage': 264.78754,
 'trailingAnnualDividendRate': 2.66,
 'trailingAnnualDividendYield': 0.007974578,
 'currency': 'USD',
 'enterpriseValue': 2455074242560,
 'profitMargins': 0.33248,
 'floatShares': 7428795636,
 'sharesOutstanding': 7435489792,
 'sharesShort': 46395809,
 'sharesShortPriorMonth': 44308393,
 'sharesShortPreviousMonthDate': 1682640000,
 'dateShortInterest': 1685491200,
 'sharesPercentSharesOut': 0.0062,
 'heldPercentInsiders': 0.00052,
 'heldPercentInstitutions': 0.73767,
 'shortRatio': 1.7,
 'shortPercentOfFloat': 0.0062,
 'impliedSharesOutstanding': 0,
 'bookValue': 26.178,
 'priceToBook': 12.864619,
 'lastFiscalYearEnd': 1656547200,
 'nextFiscalYearEnd': 1688083200,
 'mostRecentQuarter': 1680220800,
 'earningsQuarterlyGrowth': 0.094,
 'netIncomeToCommon': 69020000256,
 'trailingEps': 9.23,
 'forwardEps': 10.95,
 'pegRatio': 2.86,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 11.826,
 'enterpriseToEbitda': 24.531,
 '52WeekChange': 0.28857303,
 'SandP52WeekChange': 0.15015817,
 'lastDividendValue': 0.68,
 'lastDividendDate': 1684281600,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 336.77,
 'targetHighPrice': 400.0,
 'targetLowPrice': 232.0,
 'targetMeanPrice': 343.16,
 'targetMedianPrice': 340.0,
 'recommendationMean': 1.8,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 43,
 'totalCash': 104419000320,
 'totalCashPerShare': 14.043,
 'ebitda': 100080001024,
 'totalDebt': 79312003072,
 'quickRatio': 1.655,
 'currentRatio': 1.913,
 'totalRevenue': 207590998016,
 'debtToEquity': 40.739,
 'revenuePerShare': 27.844,
 'returnOnAssets': 0.14829001,
 'returnOnEquity': 0.38601002,
 'grossProfits': 135620000000,
 'freeCashflow': 42964873216,
 'operatingCashflow': 83441000448,
 'earningsGrowth': 0.104,
 'revenueGrowth': 0.071,
 'grossMargins': 0.68522,
 'ebitdaMargins': 0.48209998,
 'operatingMargins': 0.41415,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.4841}

In [16]:
# get historical market data
hist = msft.history(period="max")

In [17]:
# show actions (dividends, splits)
msft.actions

                           Dividends  Stock Splits
Date
1987-09-21 00:00:00-04:00       0.00           2.0
1990-04-16 00:00:00-04:00       0.00           2.0
1991-06-27 00:00:00-04:00       0.00           1.5
1992-06-15 00:00:00-04:00       0.00           1.5
1994-05-23 00:00:00-04:00       0.00           2.0
...                              ...           ...
2022-05-18 00:00:00-04:00       0.62           0.0
2022-08-17 00:00:00-04:00       0.62           0.0
2022-11-16 00:00:00-05:00       0.68           0.0
2023-02-15 00:00:00-05:00       0.68           0.0
2023-05-17 00:00:00-04:00       0.68           0.0

[87 rows x 2 columns]

In [18]:
# show dividends
msft.dividends

Date
2003-02-19 00:00:00-05:00    0.08
2003-10-15 00:00:00-04:00    0.16
2004-08-23 00:00:00-04:00    0.08
2004-11-15 00:00:00-05:00    3.08
2005-02-15 00:00:00-05:00    0.08
                             ...
2022-05-18 00:00:00-04:00    0.62
2022-08-17 00:00:00-04:00    0.62
2022-11-16 00:00:00-05:00    0.68
2023-02-15 00:00:00-05:00    0.68
2023-05-17 00:00:00-04:00    0.68
Name: Dividends, Length: 78, dtype: float64

In [19]:
# show splits
msft.splits

Date
1987-09-21 00:00:00-04:00    2.0
1990-04-16 00:00:00-04:00    2.0
1991-06-27 00:00:00-04:00    1.5
1992-06-15 00:00:00-04:00    1.5
1994-05-23 00:00:00-04:00    2.0
1996-12-09 00:00:00-05:00    2.0
1998-02-23 00:00:00-05:00    2.0
1999-03-29 00:00:00-05:00    2.0
2003-02-18 00:00:00-05:00    2.0
Name: Stock Splits, dtype: float64

In [20]:
# show financials
msft.financials
msft.quarterly_financials

,2023-03-31,2022-12-31,2022-09-30,2022-06-30,2022-03-31
Tax Effect Of Unusual Items,0.0,0.0,-10640000.0,0.0,-30430000.0
Tax Rate For Calcs,0.192917,0.192438,0.19,0.182896,0.17
Normalized EBITDA,25901000000.0,24047000000.0,24918000000.0,24513000000.0,24645000000.0
Total Unusual Items,162000000.0,-232000000.0,-56000000.0,-80000000.0,-179000000.0
Total Unusual Items Excluding Goodwill,162000000.0,-232000000.0,-56000000.0,-80000000.0,-179000000.0
Net Income From Continuing Operation Net Minority Interest,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Reconciled Depreciation,3549000000.0,3648000000.0,2790000000.0,3979000000.0,3773000000.0
Reconciled Cost Of Revenue,16128000000.0,17488000000.0,15452000000.0,16429000000.0,15615000000.0
EBIT,22352000000.0,20399000000.0,22072000000.0,20534000000.0,20693000000.0
Net Interest Income,252000000.0,210000000.0,141000000.0,56000000.0,16000000.0
Interest Expense,496000000.0,490000000.0,500000000.0,496000000.0,503000000.0
Interest Income,748000000.0,700000000.0,641000000.0,552000000.0,519000000.0
Normalized Income,18299000000.0,16425000000.0,17601360000.0,16740000000.0,16876570000.0
Net Income From Continuing And Discontinued Operation,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Total Expenses,30505000000.0,32348000000.0,28604000000.0,31331000000.0,28996000000.0
Total Operating Income As Reported,22352000000.0,20399000000.0,21518000000.0,20534000000.0,20364000000.0
Diluted Average Shares,7464000000.0,7473000000.0,7485000000.0,7506000000.0,7534000000.0
Basic Average Shares,7441000000.0,7451000000.0,7457000000.0,7474000000.0,7493000000.0
Diluted EPS,2.45,2.2,2.35,2.23,2.22
Basic EPS,2.46,2.2,2.35,2.24,2.23
Diluted NI Availto Com Stockholders,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Net Income Common Stockholders,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Net Income,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Net Income Including Noncontrolling Interests,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Net Income Continuous Operations,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0
Tax Provision,4374000000.0,3914000000.0,4016000000.0,3747000000.0,3462000000.0
Pretax Income,22673000000.0,20339000000.0,21572000000.0,20487000000.0,20190000000.0
Other Income Expense,321000000.0,-60000000.0,-87000000.0,-47000000.0,-190000000.0
Other Non Operating Income Expenses,321000000.0,-60000000.0,-31000000.0,-47000000.0,-11000000.0
Gain On Sale Of Security,162000000.0,-232000000.0,-56000000.0,21000000.0,-179000000.0
Net Non Operating Interest Income Expense,252000000.0,210000000.0,141000000.0,56000000.0,16000000.0
Interest Expense Non Operating,496000000.0,490000000.0,500000000.0,496000000.0,503000000.0
Interest Income Non Operating,748000000.0,700000000.0,641000000.0,552000000.0,519000000.0
Operating Income,22352000000.0,20399000000.0,21518000000.0,20534000000.0,20364000000.0
Operating Expense,14377000000.0,14860000000.0,13152000000.0,14902000000.0,13381000000.0
Research And Development,6984000000.0,6844000000.0,6628000000.0,6849000000.0,6306000000.0
Selling General And Administration,7393000000.0,8016000000.0,6524000000.0,8053000000.0,7075000000.0
Selling And Marketing Expense,5750000000.0,5679000000.0,5126000000.0,6304000000.0,5595000000.0
General And Administrative Expense,1643000000.0,2337000000.0,1398000000.0,1749000000.0,1480000000.0
Other Gand A,1643000000.0,2337000000.0,1398000000.0,1749000000.0,1480000000.0
Gross Profit,36729000000.0,35259000000.0,34670000000.0,35436000000.0,33745000000.0
Cost Of Revenue,16128000000.0,17488000000.0,15452000000.0,16429000000.0,15615000000.0
Total Revenue,52857000000.0,52747000000.0,50122000000.0,51865000000.0,49360000000.0
Operating Revenue,52857000000.0,52747000000.0,50122000000.0,51865000000.0,49360000000.0

In [21]:
# show cashflow
msft.cashflow
msft.quarterly_cashflow

,2023-03-31,2022-12-31,2022-09-30,2022-06-30,2022-03-31
Free Cash Flow,17834000000.0,4899000000.0,16915000000.0,17758000000.0,20046000000.0
Repurchase Of Capital Stock,-5509000000.0,-5459000000.0,-5573000000.0,-8757000000.0,-8822000000.0
Repayment Of Debt,0.0,-750000000.0,-1000000000.0,0.0,-4197000000.0
Issuance Of Capital Stock,536000000.0,243000000.0,575000000.0,461000000.0,477000000.0
Capital Expenditure,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0,-5340000000.0
End Cash Position,26562000000.0,15646000000.0,22884000000.0,13931000000.0,12498000000.0
Beginning Cash Position,15646000000.0,22884000000.0,13931000000.0,12498000000.0,20604000000.0
Effect Of Exchange Rate Changes,29000000.0,88000000.0,-230000000.0,-198000000.0,24000000.0
Changes In Cash,10887000000.0,-7326000000.0,9183000000.0,1631000000.0,-8130000000.0
Financing Cash Flow,-10290000000.0,-11349000000.0,-10883000000.0,-13269000000.0,-17345000000.0
Cash Flow From Continuing Financing Activities,-10290000000.0,-11349000000.0,-10883000000.0,-13269000000.0,-17345000000.0
Net Other Financing Charges,-258000000.0,-317000000.0,-264000000.0,-341000000.0,-158000000.0
Cash Dividends Paid,-5059000000.0,-5066000000.0,-4621000000.0,-4632000000.0,-4645000000.0
Common Stock Dividend Paid,-5059000000.0,-5066000000.0,-4621000000.0,-4632000000.0,-4645000000.0
Net Common Stock Issuance,-4973000000.0,-5216000000.0,-4998000000.0,-8296000000.0,-8345000000.0
Common Stock Payments,-5509000000.0,-5459000000.0,-5573000000.0,-8757000000.0,-8822000000.0
Common Stock Issuance,536000000.0,243000000.0,575000000.0,461000000.0,477000000.0
Net Issuance Payments Of Debt,0.0,-750000000.0,-1000000000.0,0.0,-4197000000.0
Net Long Term Debt Issuance,0.0,-750000000.0,-1000000000.0,0.0,-4197000000.0
Long Term Debt Payments,0.0,-750000000.0,-1000000000.0,0.0,-4197000000.0
Investing Cash Flow,-3264000000.0,-7150000000.0,-3132000000.0,-9729000000.0,-16171000000.0
Cash Flow From Continuing Investing Activities,-3264000000.0,-7150000000.0,-3132000000.0,-9729000000.0,-16171000000.0
Net Other Investing Changes,-1686000000.0,-301000000.0,-860000000.0,-1138000000.0,-1181000000.0
Net Investment Purchase And Sale,5330000000.0,104000000.0,4360000000.0,-457000000.0,9069000000.0
Sale Of Investment,14393000000.0,11703000000.0,9373000000.0,4462000000.0,17792000000.0
Purchase Of Investment,-9063000000.0,-11599000000.0,-5013000000.0,-4919000000.0,-8723000000.0
Net Business Purchase And Sale,-301000000.0,-679000000.0,-349000000.0,-1263000000.0,-18719000000.0
Purchase Of Business,-301000000.0,-679000000.0,-349000000.0,-1263000000.0,-18719000000.0
Net PPE Purchase And Sale,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0,-5340000000.0
Purchase Of PPE,-6607000000.0,-6274000000.0,-6283000000.0,-6871000000.0,-5340000000.0
Operating Cash Flow,24441000000.0,11173000000.0,23198000000.0,24629000000.0,25386000000.0
Cash Flow From Continuing Operating Activities,24441000000.0,11173000000.0,23198000000.0,24629000000.0,25386000000.0
Change In Working Capital,1843000000.0,-10347000000.0,1873000000.0,1473000000.0,3072000000.0
Change In Other Working Capital,1233000000.0,-8049000000.0,-2912000000.0,11555000000.0,882000000.0
Change In Other Current Liabilities,1721000000.0,2076000000.0,-3836000000.0,3499000000.0,1725000000.0
Change In Other Current Assets,598000000.0,-457000000.0,-998000000.0,-3145000000.0,-633000000.0
Change In Payables And Accrued Expense,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0,520000000.0
Change In Payable,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0,520000000.0
Change In Account Payable,-407000000.0,-2058000000.0,-1567000000.0,2659000000.0,520000000.0
Change In Inventory,106000000.0,1305000000.0,-543000000.0,-461000000.0,-279000000.0
Change In Receivables,-1408000000.0,-3164000000.0,11729000000.0,-12634000000.0,857000000.0
Changes In Account Receivables,-1408000000.0,-3164000000.0,11729000000.0,-12634000000.0,857000000.0
Stock Based Compensation,2465000000.0,2538000000.0,2192000000.0,1997000000.0,1906000000.0
Deferred Tax,-1675000000.0,-1305000000.0,-1191000000.0,283000000.0,-198000000.0
Deferred Income Tax,-1675000000.0,-1305000000.0,-1191000000.0,283000000.0,-198000000.0
Depreciation Amortization Depletion,3549000000.0,3648000000.0,2790000000.0,3979000000.0,3773000000.0
Depreciation And Amortization,3549000000.0,3648000000.0,2790000000.0,3979000000.0,3773000000.0
Depreciation,3549000000.0,3648000000.0,2790000000.0,3979000000.0,3773000000.0
Operating Gains Losses,-40000000.0,214000000.0,-22000000.0,157000000.0,105000000.0
Net Income From Continuing Operations,18299000000.0,16425000000.0,17556000000.0,16740000000.0,16728000000.0

In [22]:
# show news
msft.news

[{'uuid': 'd31aad7f-b7f2-3fb4-a58f-19212a6699d4',
  'title': 'Nvidia Is Getting a Big Boost in a Fast-Growing Market, and It Is Not AI',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/d31aad7f-b7f2-3fb4-a58f-19212a6699d4/nvidia-is-getting-a-big-boost.html',
  'providerPublishTime': 1687442940,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/YfjEnGWZ2v4uqlhWc5FoVw--~B/aD0xNDE0O3c9MjExOTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/d33afbc660e2674b2b20ebdf4634f4a6',
     'width': 2119,
     'height': 1414,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/cWoYb.rlciQjD49_1KikrQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/d33afbc660e2674b2b20ebdf4634f4a6',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'MSFT']},
 {'uuid': '71e55d95-b625-314e-aea3-8ed87909949b',
  'title': 'Dow Jones Falls After Jobless Claims; Powell Speech Now; Tesla Stock Slides On Downgrade',
  'publisher': "Investor's Business Daily",
  'link': 'https://finance.yahoo.com/m/71e55d95-b625-314e-aea3-8ed87909949b/dow-jones-falls-after-jobless.html',
  'providerPublishTime': 1687442912,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/.bZtsgnchEamZO3REAT9sQ--~B/aD01NjM7dz0xMDAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/f507e9a69bd7ba001d8325d21822e555',
     'width': 1000,
     'height': 563,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/WS3H.kxz4qvCSKfewkjczA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/ibd.com/f507e9a69bd7ba001d8325d21822e555',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['^DJI', 'TSLA', 'MSFT', 'COMP', 'DXCM']},
 {'uuid': 'f6295d22-647b-3caa-b03e-15003c7fef78',
  'title': 'Microsoft’s Activision Acquisition Gets Its Day In Court. A Loss Will Kill the Deal.',
  'publisher': 'Barrons.com',
  'link': 'https://finance.yahoo.com/m/f6295d22-647b-3caa-b03e-15003c7fef78/microsoft%E2%80%99s-activision.html',
  'providerPublishTime': 1687435140,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/..RUt9zvTDReiSJ7tdFjdw--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/6547f97da62d453be07e57b509f60dd1',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/QvlAs9Q7rlQkxeF2uYFrSQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/Barrons.com/6547f97da62d453be07e57b509f60dd1',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'ATVI']},
 {'uuid': 'a32ec193-d1d6-373f-a4aa-64f989d7aaee',
  'title': 'Everything to know about the Microsoft-Activision Blizzard hearing that starts today',
  'publisher': 'Fortune',
  'link': 'https://finance.yahoo.com/news/everything-know-microsoft-activision-blizzard-110953409.html',
  'providerPublishTime': 1687432193,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/78F1SGYhhhVwQusoHs7kPQ--~B/aD0xMzY1O3c9MjA0ODthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/fortune_175/4e33cd286f7e9d893b2deb5ea11c85fd',
     'width': 2048,
     'height': 1365,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/S9bzOdLCBzQBFLOKnp.Bhg--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/fortune_175/4e33cd286f7e9d893b2deb5ea11c85fd',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'ATVI']},
 {'uuid': '1259b84f-8da7-3b70-809c-b32db3282f96',
  'title': 'Nvidia Now Tops Tesla as ESG Funds Ratchet Up Exposure to AI',
  'publisher': 'Bloomberg',
  'link': 'https://finance.yahoo.com/news/nvidia-more-popular-tesla-another-190000799.html',
  'providerPublishTime': 1687431543,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/uvIKx22HNav1TUgzq2aawg--~B/aD02NzU7dz0xMjAwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_markets_842/30251671f39c6a71a0e731b9c8911575',
     'width': 1200,
     'height': 675,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/XwyY3q_kq4pOgXBsmDAdiQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/bloomberg_markets_842/30251671f39c6a71a0e731b9c8911575',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['NVDA', 'MSFT']},
 {'uuid': 'dee2a543-1b65-329d-ab64-4e9baf55fb8d',
  'title': "FTC to argue Microsoft's deal to buy Activision should be paused",
  'publisher': 'Reuters',
  'link': 'https://finance.yahoo.com/news/ftc-argue-microsofts-deal-buy-100359990.html',
  'providerPublishTime': 1687428239,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/nNenub2PCVJ7rULEaZUa1A--~B/aD01MDU7dz04MDA7YXBwaWQ9eXRhY2h5b24-/https://media.zenfs.com/en/reuters-finance.com/1fa095229c1c4bbf65065fd89253897f',
     'width': 800,
     'height': 505,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/F0xVC83DvnV2PZSvnR6xlw--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/reuters-finance.com/1fa095229c1c4bbf65065fd89253897f',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['MSFT', 'ATVI']},
 {'uuid': '247ab8ac-980f-3cde-9fbe-d7bc0ed639e9',
  'title': 'Microsoft and Activision to face FTC challenge to $75bn deal',
  'publisher': 'Financial Times',
  'link': 'https://finance.yahoo.com/m/247ab8ac-980f-3cde-9fbe-d7bc0ed639e9/microsoft-and-activision-to.html',
  'providerPublishTime': 1687428035,
  'type': 'STORY',
  'relatedTickers': ['MSFT', 'ATVI']},
 {'uuid': 'c827624f-ce15-3c3c-84af-f28b50e6152f',
  'title': '$1.2 Trillion Generative AI Boom in 3 Industries: Here Are the Top Stocks to Buy',
  'publisher': 'Motley Fool',
  'link': 'https://finance.yahoo.com/m/c827624f-ce15-3c3c-84af-f28b50e6152f/%241.2-trillion-generative-ai.html',
  'providerPublishTime': 1687427400,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/F4tPL_8bi1GR3g5oKB12yw--~B/aD0xMjcwO3c9MjM1OTthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/motleyfool.com/a132458a1e2ea2b003f9b9d59aa03036',
     'width': 2359,
     'height': 1270,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/.uAMmgJ1kvfp_vdAjiJSww--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/motleyfool.com/a132458a1e2ea2b003f9b9d59aa03036',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['SDA', 'WMT', 'MSFT', 'AMZN']}]